#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_ENV_FILE="${OPENCLAW_ENV_FILE:-$ROOT_DIR/.env}"
DOCKER_ENV_FILE="${OPENCLAW_DOCKER_ENV_FILE:-$ROOT_DIR/.openclaw-docker.env}"
COMPOSE_FILE="${OPENCLAW_DOCKER_COMPOSE_FILE:-$ROOT_DIR/docker-compose.openclaw.yml}"
ACTION="${1:-up}"
if [[ $# -gt 0 ]]; then
  shift
fi

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

usage() {
  cat <<'EOF'
Usage: bash scripts/openclaw-docker.sh [up|build|bootstrap|down|logs|ps|shell]

Default action is `up`, which:
  1. creates the persisted host dirs
  2. writes a container-safe env file
  3. builds the local OpenClaw image for this workspace
  4. bootstraps/configures OpenClaw inside the CLI container
  5. starts the gateway container
EOF
}

require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose is required" >&2
  exit 1
fi

if [[ ! -f "$BASE_ENV_FILE" ]]; then
  echo "missing $BASE_ENV_FILE" >&2
  echo "copy .env.example to .env and fill in the values first" >&2
  exit 1
fi

# shellcheck disable=SC1091
source "$ROOT_DIR/scripts/load-env.sh" "$BASE_ENV_FILE"

STATE_DIR="${OPENCLAW_DOCKER_STATE_DIR:-$HOME/.openclaw}"
PROJECT_NAME="${OPENCLAW_DOCKER_PROJECT_NAME:-chibaclaw}"
IMAGE="${OPENCLAW_DOCKER_IMAGE:-chibaclaw-openclaw:latest}"
BASE_IMAGE="${OPENCLAW_DOCKER_BASE_IMAGE:-ghcr.io/openclaw/openclaw:latest}"
UV_IMAGE="${OPENCLAW_DOCKER_UV_IMAGE:-ghcr.io/astral-sh/uv:0.8.17}"
RUNTIME_UID="${OPENCLAW_DOCKER_UID:-${SUDO_UID:-$(id -u)}}"
RUNTIME_GID="${OPENCLAW_DOCKER_GID:-${SUDO_GID:-$(id -g)}}"
EXPOSE_HOST="${OPENCLAW_GATEWAY_EXPOSE_HOST:-127.0.0.1}"
CONTAINER_BIND="${OPENCLAW_DOCKER_GATEWAY_BIND:-lan}"
SKIP_SKILL_SETUP="${OPENCLAW_SKIP_SKILL_SETUP:-1}"

mkdir -p "$STATE_DIR" "$ROOT_DIR/.openclaw"
if [[ "$(id -u)" -eq 0 ]]; then
  chown -R "$RUNTIME_UID:$RUNTIME_GID" "$STATE_DIR" "$ROOT_DIR/.openclaw"
fi

cat "$BASE_ENV_FILE" >"$DOCKER_ENV_FILE"
cat >>"$DOCKER_ENV_FILE" <<EOF

# Generated by scripts/openclaw-docker.sh
OPENCLAW_DOCKER_IMAGE=$IMAGE
OPENCLAW_DOCKER_BASE_IMAGE=$BASE_IMAGE
OPENCLAW_DOCKER_UV_IMAGE=$UV_IMAGE
OPENCLAW_DOCKER_PROJECT_NAME=$PROJECT_NAME
OPENCLAW_DOCKER_STATE_DIR=$STATE_DIR
OPENCLAW_DOCKER_UID=$RUNTIME_UID
OPENCLAW_DOCKER_GID=$RUNTIME_GID
OPENCLAW_HOST_WORKSPACE_DIR=$ROOT_DIR
OPENCLAW_GATEWAY_EXPOSE_HOST=$EXPOSE_HOST
OPENCLAW_ENV_FILE=/workspace/$(basename "$DOCKER_ENV_FILE")
OPENCLAW_WORKSPACE_DIR=/workspace
OPENCLAW_GATEWAY_BIND=$CONTAINER_BIND
OPENCLAW_INSTALL_GATEWAY_SERVICE=0
OPENCLAW_START_GATEWAY_SERVICE=0
OPENCLAW_SKIP_SKILL_SETUP=$SKIP_SKILL_SETUP
EOF

compose() {
  docker compose \
    --env-file "$DOCKER_ENV_FILE" \
    -p "$PROJECT_NAME" \
    -f "$COMPOSE_FILE" \
    "$@"
}

build_image() {
  compose build openclaw-cli
}

bootstrap() {
  build_image
  compose run --rm --no-deps openclaw-cli "bash /workspace/scripts/install-openclaw-workspace.sh"
}

case "$ACTION" in
  up)
    bootstrap
    compose up -d openclaw-gateway
    cat <<EOF
chibaclaw: docker gateway is up
compose_project=$PROJECT_NAME
state_dir=$STATE_DIR
workspace=$ROOT_DIR
container_user=$RUNTIME_UID:$RUNTIME_GID
gateway=http://$EXPOSE_HOST:$OPENCLAW_GATEWAY_PORT

Suggested SSH tunnel from your laptop:
  ssh -N -L $OPENCLAW_GATEWAY_PORT:127.0.0.1:$OPENCLAW_GATEWAY_PORT <user>@<server>
EOF
    ;;
  build)
    build_image
    ;;
  bootstrap)
    bootstrap
    ;;
  down)
    compose down
    ;;
  logs)
    compose logs -f "${1:-openclaw-gateway}"
    ;;
  ps)
    compose ps
    ;;
  shell)
    compose run --rm --no-deps openclaw-cli "exec bash"
    ;;
  help | --help | -h)
    usage
    ;;
  *)
    echo "unknown action: $ACTION" >&2
    usage >&2
    exit 1
    ;;
esac
