#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=skills/eden-tools/scripts/lib.sh
source "$SCRIPT_DIR/scripts/lib.sh"

OUTPUT_DIR="$EDEN_REPO_ROOT/outputs/eden-tools"
LOCAL_NOTES_FILE="$OUTPUT_DIR/api-notes.local.md"
SOURCE_REPO="$(eden_source_repo)"

mkdir -p "$OUTPUT_DIR"

cat > "$LOCAL_NOTES_FILE" <<EOF
# Eden Tool API Notes (Local)

_Generated by \`bash skills/eden-tools/setup.sh\`._

Resolved source repo: \`$SOURCE_REPO\`

## Source Files

- \`$SOURCE_REPO/apps/api/src/routes/tools.ts\`
- \`$SOURCE_REPO/apps/api/src/routes/tasks.ts\`
- \`$SOURCE_REPO/packages/sdk-ts/src/generated/openapi.ts\`
EOF

if ! command -v curl >/dev/null 2>&1; then
  echo "eden-tools: curl is required" >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "eden-tools: node is required" >&2
  exit 1
fi

API_URL="${EDEN_API_URL:-}"
API_KEY="${EDEN_API_KEY:-}"

if [[ -z "$API_URL" || -z "$API_KEY" ]]; then
  echo "eden-tools: ready"
  echo "source_repo=$SOURCE_REPO"
  echo "local_api_notes=$LOCAL_NOTES_FILE"
  echo "set EDEN_API_URL and EDEN_API_KEY to enable live calls"
  exit 0
fi

TMP_DIR="$(eden_make_tmpdir)"
trap 'rm -rf "$TMP_DIR"' EXIT
RESPONSE_FILE="$TMP_DIR/tools-probe.json"
STATUS_CODE="$(eden_curl_json GET "/v1/tools?limit=1" "" "$RESPONSE_FILE")"

if [[ "$STATUS_CODE" != "200" ]]; then
  echo "eden-tools: API probe failed ($STATUS_CODE)" >&2
  eden_pretty_json_file "$RESPONSE_FILE" 0 >&2
  exit 1
fi

echo "eden-tools: ready"
echo "api_url=$(eden_api_url)"
echo "source_repo=$SOURCE_REPO"
echo "local_api_notes=$LOCAL_NOTES_FILE"
